### ISSUE TITLE
Engine "code-davinci-001" not found

### ISSUE THREAD

**Issue by Andrea-Augello** [tom-doerr/vim_codex#12]
Even if the new update changed the model name from 'davinci-codex' to 'code-davinci-001' calls to CreateCompletion still give the error `openai.error.InvalidRequestError: Engine not found`.
I tried a clean install and the problem persists.
I am using python 3.8.10, openai version 0.10.2, and vim 8.2

**Comment by tom-doerr** [comment]
Are you sure you do have access to Codex? Having access to the OpenAI API is not enough.

**Comment by tom-doerr** [comment]
https://github.com/tom-doerr/vim_codex/issues/4

**Comment by Andrea-Augello** [comment]
Thank you for your quick response, my API gives me access to the codex, and I
have been using this plug-in for months without any issue.

**Comment by tom-doerr** [comment]
You might want to contact support@openai.com.

**Comment by tom-doerr** [comment]
Were you able to fix the issue?

**Comment by Andrea-Augello** [comment]
The plugin update was just a coincidence.
The error was caused by the API usage exceeding the available credits
