### ISSUE TITLE
Consider removing the screenshot / gifs from the main repository

### ISSUE THREAD

**Issue by oddlama** [tom-doerr/vim_codex#16]
By including the screenshot / gif in your main repository, every user will have a copy of these gigantic files for no reason at all, when all they need is the few kilobytes of vimscript / python. Unfortunately a lot of plugins do this and it unnecessarily bloats the whole vim installation.

A much easier and better alternative is to use a permalink generated by github for these files and use that link in the repo instead. You can generate such a link by simply dropping the file into a new github issue. Even if you discard the issue afterwards, the genereated link will be a permalink to the uploaded file on github's servers.

Most plugin managers do shallow clones (` --depth 1`) by default, so changing this now will still benefit all users, as history isn't kept when updating.

**Comment by tom-doerr** [comment]
Hi @oddlama, thanks for opening the issue. Yes, that is a lot of unnecessary data, for my newer projects I added links instead of adding GIFs to the repo itself, I did not know that I can upload files into issues and link to them. PRs are welcome ;)
