### ISSUE TITLE
Make output configurable to only one line at a time

### ISSUE THREAD

**Issue by abatilo** [tom-doerr/vim_codex#2]
Right now, even if I just want vim_codex to create a single line of generation, I get a bunch of extra lines as well.

Otherwise, great plugin and thanks for making it possible for vim users to try this next generation tech!

**Comment by tom-doerr** [comment]
Added a `CreateCompletionLine` command that you can map. Does that do what you want?

**Comment by abatilo** [comment]
I think that'll do great! Thanks!
