### ISSUE TITLE
How to deal with discontinuation of Codex?

### ISSUE THREAD

**Issue by clotodex** [tom-doerr/vim_codex#22]
I can see a few options:
- discontinue in favor of other plugins (no idea if some already exists with chatgpt backend and such)
- switch underlying model to gpt3-turbo or gpt4 and change prompt structure to improve output
- switch to gpt3 or similar model and keep the plugin as-is
- integrate with ChatGPT session token, login challenge if expired, to allow continued free use

What do you think?

**Comment by VictorTaelin** [comment]
Wondering that too. Codex served me very well. Mapping it to complete my files based on its contents was superb. What is everyone using in its place?

**Comment by slacksystem** [comment]
I'm working on creating a working version in my fork but
- While I have some experience, I'm just a hobbyist
- While it should be doable for me, I have a limited amount of time I can spend on it
So it's likely I can get it working but timeline is unknown at this point and if there's another option right now that's good we should go with that instead.

ETA: I'd also be happy to collaborate with someone on it as well.
