### ISSUE TITLE
Requires multiple calls of create completion command to finish

### ISSUE THREAD

**Issue by SijanC147** [tom-doerr/vim_codex#3]
great work on this first of all. I'm trying to recreate the ethereum example in the readme. The code gets generated ok however for some reason it stops after a few lines and i have to call the command again for it to continue generating the code. The example in the readme took me about 4 invocations of the command.

**Comment by SijanC147** [comment]
nevermind, i figured out it's a function of the max tokens argument, and after trying to increase that, i understand why you set it the way you did 😂 

keep up the good work.

**Comment by tom-doerr** [comment]
Glad you like the plugin. :)  You could increase the max tokens and use the new `CreateCompletionLine` function when you want just a single line of completion: https://github.com/tom-doerr/vim_codex/issues/2

**Comment by tom-doerr** [comment]
I now added the option to give the number of tokens you want as an argument, e.g. `CreateCompletion 1000`.
