### ISSUE TITLE
openaiapirc

### ISSUE THREAD

**Issue by luisdavim** [tom-doerr/vim_codex#6]
Why not use the same `openaiapirc` file for the auth like it's done on the `zsh` plugin?

**Comment by tom-doerr** [comment]
The vim plugin was my first plugin, I didn't know how configuration files are usually written in Unix. I plan to switch the vim plugin to the `openaiapirc` config file.

**Comment by tom-doerr** [comment]
Updated it to use the `openaiapirc`.
