### ISSUE TITLE
Auth error on completion (fresh install)

### ISSUE THREAD

**Issue by JoseConseco** [tom-doerr/vim_codex#7]
The error I get:  
![image](https://user-images.githubusercontent.com/13521338/138348393-2ce609b3-706a-45c1-a428-310a725d3b80.png)

I have put  AUTH.py into /codi.vim/python/   -  and the content of files is just api key  string. Maybe AUTH.py should have other data included? There is no info about format of AUTH.py file...

btw.  vim_codex was installed with nvim packer into:
![image](https://user-images.githubusercontent.com/13521338/138348835-5f70e42d-c2e7-4670-bf55-8e97bec7db36.png)

**Comment by tom-doerr** [comment]
That appears to be the wrong location for the AUTH.py file.  The file should already exist at ...`packer/start/vim_codex/python/AUTH.py`. You need to enter your data there.

**Comment by JoseConseco** [comment]
Ok, that is weird - first I created AUTH file manually, but now I see the content is overwritten with:
```
ORGANIZATION_ID=''
SECRET_KEY=''     
```
After providing the data, all works ok.

**Comment by tom-doerr** [comment]
It looks like you created .../start/codi.vim/python/AUTH.py  and not .../start/vim_codex/python/AUTH.py . My guess would be you hit Tab at .../start/co
